version: '2'

services:

  nginx:
    image: nginx
    ports:
      - 8080:8080
    container_name: web
    networks:
      - local
    volumes:
      - ./data/www:/usr/share/nginx/html
      - ./conf/nginx/bnk.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    restart: always

  php:
    build: ./build/php
    networks:
      - local
    volumes:
      - ./data/www:/usr/share/nginx/html
      - ./conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mariadb
    restart: always

  mariadb:
    image: mariadb
    networks:
      - local
    environment:
      MYSQL_ROOT_PASSWORD: wdRbbQtpdf
    volumes:
      - ./data/db:/var/lib/mysql
      - ./conf/mariadb/my.cnf:/etc/mysql/conf.d/bnk.cnf
    restart: always

networks:

  local:
    driver: bridge